#!/bin/bash

echo Setting up database and user

mysql -u root -p${MARIADB_ROOT_PASSWORD} <<EOF
CREATE DATABASE $MDB_UNITTEST_DB;

CREATE USER '$MDB_USER'@'localhost' IDENTIFIED BY '$MDB_PASS';
GRANT ALL ON $MDB_UNITTEST_DB.* TO $MDB_USER@localhost;
CREATE USER '$MDB_USER'@'127.0.0.1' IDENTIFIED BY '$MDB_PASS';
GRANT ALL ON $MDB_UNITTEST_DB.* TO $MDB_USER@127.0.0.1;
EOF